apiVersion: v1
kind: Pod
metadata:
  name: api-client
  namespace: default
  labels:
    app: api-client
spec:
  containers:
    - name: client
      image: nicolaka/netshoot:latest
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash"]
      args: ["-c", "while true; do sleep 3600; done"]
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "50m"
          memory: "64Mi"