apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: migration
          image: migration-api:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: postgres-headless
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
      restartPolicy: Never
  backoffLimit: 3
