apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-metrics-api
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: api
          image: slack-metrics-api:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          env:
            - name: DB_HOST
              value: postgres-headless
            - name: DB_SSLMODE
              value: "disable"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi