apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

labels:
  - pairs:
      environment: development

resources:
  - ../../base/api

patches:
  - target:
      kind: Deployment
      name: slack-metrics-api
    path: deployment-patch.yaml

configMapGenerator:
  - name: slack-metrics-api-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - METRICS_TYPE=standard
      - REPORT_FORMAT=simple
      - ENVIRONMENT=development