apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: slack-metrics-prod

labels:
  - pairs:
      environment: production

resources:
  - ../../base/api
  - account-config.yaml

patches:
  - target:
      kind: Deployment
      name: slack-metrics-api
    path: deployment-patch.yaml
  - target:
      kind: NetworkPolicy
      name: slack-metrics-api-netpol
    path: networkpolicy-patch.yaml
  - target:
      kind: HorizontalPodAutoscaler
      name: slack-metrics-api-hpa
    path: hpa-patch.yaml

configMapGenerator:
  - name: slack-metrics-api-config
    behavior: merge
    literals:
      - LOG_LEVEL=warning
      - METRICS_TYPE=database
      - REPORT_FORMAT=detailed
      - ENVIRONMENT=production

replacements:
  - source:
      kind: ConfigMap
      name: account-config
      fieldPath: data.aws_account_id
    targets:
      - select:
          kind: ServiceAccount
          name: slack-metrics-api
        fieldPaths:
          - metadata.annotations.[eks.amazonaws.com/role-arn]
        options:
          delimiter: ':'
          index: 4