apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
  namespace: default
spec:
  containers:
  - name: postgres-client
    image: postgres:15-alpine
    command: ["sleep", "3600"]
    env:
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD